version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./app:/usr/src/app:delegated
    ports:
        - ${REACT_APP_DEV_PORT}:${REACT_APP_DEV_PORT}
        - ${REACT_APP_PRD_PORT}:${REACT_APP_PRD_PORT}
    command: sh -c "npm start"
    stdin_open: true
    env_file: .env
