version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./app:/usr/src/app:delegated
    ports:
        - ${REACT_APP_DEV_PORT}:${REACT_APP_DEV_PORT}
        - ${REACT_APP_PRD_PORT}:${REACT_APP_PRD_PORT}
    command: sh -c "echo Run at http://localhost:${REACT_APP_DEV_PORT}/ && npm start"
    # command: sh -c "yarn run start-prod"
    stdin_open: true
    env_file: .env
